#!/bin/sh
##SBATCH -q urgent
##SBATCH -q debug
#SBATCH --cluster=c5
#SBATCH -t 03:00:00
#SBATCH -A nggps_psd 
#SBATCH -N 80    
#SBATCH -J C384_hybcov_6hourly
#SBATCH -e C384_hybcov_6hourly.err
#SBATCH -o C384_hybcov_6hourly.out

export NODES=$SLURM_NNODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='gaeac5'

# for control forecast
if [ $NODES -eq 10 ]; then
  # 10 nodes, 2 threads
  export control_threads=2
  export control_proc=1280
  export write_groups_ctl=4 # write groups for control forecast.
  export write_tasks_ctl=16
  export layout_ctl="8,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 20 ]; then
  # 20 nodes, 4 threads
  export control_threads=4
  export control_proc=2560
  export write_groups_ctl=4 # write groups for control forecast.
  export write_tasks_ctl=16
  export layout_ctl="8,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 40 ]; then
  # 40 nodes, 8 threads
  export control_threads=8
  export control_proc=5120
  export write_groups_ctl=4 # write groups for control forecast.
  export write_tasks_ctl=24
  export layout_ctl="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
elif [ $NODES -eq 80 ]; then
  # 80 nodes, 16 threads
  export control_threads=16
  export control_proc=10240
  export write_groups_ctl=4 # write groups for control forecast.
  export write_tasks_ctl=24
  export layout_ctl="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

# for ensemble forecast and GSI
#export fg_proc=$corespernode 
export fg_proc=`expr 2 \* $corespernode`
export fg_threads=1
export write_groups=1
if [ $corespernode -eq 128 ]; then
export enkf_threads=32
export gsi_control_threads=32
export write_groups=1
export write_tasks=16 
export layout="8, 5" 
elif [ $corespernode -eq 192 ]; then
export enkf_threads=48
export gsi_control_threads=48
export write_groups=4
export write_tasks=12 
export layout="4, 6" 
#export write_groups=4
#export write_tasks=24 
#export layout="8, 6" 
elif [ $corespernode -eq 36 ]; then
export enkf_threads=36
export gsi_control_threads=9
export write_groups=1
#export write_tasks=12 
#export layout="2, 2" 
export write_tasks=18 
export layout="3, 3" 
elif [ $corespernode -eq 32 ]; then
export enkf_threads=8
export gsi_control_threads=4
export write_groups=1
export write_tasks=8 
export layout="2, 2" 
elif [ $corespernode -eq 24 ]; then
export layout="3, 1" 
else
echo "layout for ensemble forecast not specified for corespernode=$corespernode"
exit 1
fi
